### ISSUE TITLE
cfn.nagscan has findings, but they do not arrive in SonarQube

### ISSUE THREAD

**Issue by BenjenJones** [Hack23/sonar-cloudformation-plugin#126]
Hello,

I used an older version of the sonarqube cfn plugin, that was manually installed. Today I got an auto update for that to the version 2.0.4

Since then, the findings in the cfn.nagscan json file, are not shown in SonarQube anymore.

Output is:

INFO: Sensor Cloudformation Check [cloudformation]
INFO: Process cfn-nag reports
INFO: sonar.cfn.nag.reportFiles=cfn.nagscan
INFO: Processing:cfn.nagscan
INFO: Looking for cloudformation template matching:cfn.json
INFO: matching:cfn.json = cfn.json
INFO: Load project repositories
INFO: Load project repositories (done) | time=31ms
INFO: Looking for cloudformation template matching:db-stack.cfn.json
INFO: matching:db-stack.cfn.json = db-stack.cfn.json
INFO: Process cfn-nag reports (done) | time=345ms
INFO: Sensor Cloudformation Check [cloudformation] (done) | time=346ms

But SonarQube had the 6 found issues removed in todays version.

I tested around a bit, moving the files to other locations, but no success.

For information, the 2 files are in the main directory, since we use deployment repositories apart from our source-code.

Best,
Ben

**Comment by BenjenJones** [comment]
ok,

I found the new rules. They are categorized under YAML rules.
This is not very user friendly.
Do you include the normal YAML rules in your Profile?
Also, we use JSON templates, so it didn't came to my mind, to have a look at the YAML Profile, just found it by accident.

Maybe it would be better, to add a separate Profile for the CloudFormation Section.

**Comment by pethers** [comment]
Based on requirements for being included in marketplace, the cfn language has been removed. 

https://community.sonarsource.com/t/new-release-sonar-cloudformation-plugin-1-0-2/14021/5 , needed to comply to be included in marketplace.

Can make further releases of 1.x branch with old behavior if needed.

**Comment by BenjenJones** [comment]
Hey,

no you dont need to, I just needed to understand how it is working.
So for now, I extended the CloudFormation Rules and added the YAML Sonar Way rules to it.
Should work now.
Before I opened the ticket, I tried for ~3h to get this working.
And right after I created the issue, I found the Cloudformation Rules.

So, Ticket can be closed I think.
Thanks and sorry for disturbing :)

Best,
Ben
