### ISSUE TITLE
Release Assets

### ISSUE THREAD

**Issue by Schoaib** [Hack23/sonar-cloudformation-plugin#151]
Hi,

Is it possible to add .jar in release assets, this helps greatly when we have to add plugins on sonarqube installation done via helm charts.

Thanks

**Comment by pethers** [comment]
Hi,

Would be possible but have to do it in a manual step,  currently just publish to maven central.

Is is not possible to download from maven central or https://mvnrepository.com/artifact/com.hack23.sonar/sonar-cloudformation-plugin instead ?

Never heard of  helm charts.

**Comment by Schoaib** [comment]
Hi Pether,

Thanks for the reply. Sure i can add the link to maven central repository instead. The reason I asked for it as I see all other sonar plugins providing a jar file on the release assets.

cheers
