### ISSUE TITLE
.nag output from cfn_nag now looks like .nagscan output

### ISSUE THREAD

**Issue by JoelPagliuca** [Hack23/sonar-cloudformation-plugin#202]
Worth noting that `cfn_nag 0.6.8` output now looks like the `cfn_nag_scan` output and causes a jackson parse error.

<img width="541" alt="image" src="https://user-images.githubusercontent.com/9686709/95537233-e452a580-0a38-11eb-8b28-24c7513cfc81.png">

The difference in the output is it's in an array now and has the filename key.

We're able to work around it (naming the file as a nagscan output file) but maybe worth either updating docos or changing the behavior

**Comment by JoelPagliuca** [comment]
It is October, maybe worth chucking the `hacktoberfest` label on the repo ;)

**Comment by pethers** [comment]
Thanks for reporting this. Also added the label hacktoberfest on the repo.
