### ISSUE TITLE
Handing same filename in different directories 

### ISSUE THREAD

**Issue by tzvetkov75** [Hack23/sonar-cloudformation-plugin#210]
Hi, 
very nice plugin. It seems to have problems whem there are same template names but in a different directories, like 

/folder_1/test.yaml
/folder_2/test.yaml

the result nagscan report is correct but the plug-in fails to map the issues between the files. Everything is mapped to the first file. 

Many thanks

**Comment by tzvetkov75** [comment]
👍

**Comment by pethers** [comment]
Thanks for reporting this.

**Comment by pethers** [comment]
Looks like a problem in https://github.com/Hack23/sonar-cloudformation-plugin/blob/master/src/main/java/com/hack23/sonar/cloudformation/CloudformationSensor.java , removing the path and just return first filename that match.

**Comment by tzvetkov75** [comment]
yes, thanks. Keeping the path relative to baseDir as in the scan report will be solution. May be the same bug is also in multiple nag reports mapping to file. (.nag)
