### ISSUE TITLE
Plugin Issues - Setup

### ISSUE THREAD

**Issue by ilyas-ixm** [Hack23/sonar-cloudformation-plugin#363]
Hi,
I have two questions;

1. Why is the latest version changed to Release 1.7.2(legacy) from Release 2.0.10? Is this an older version? Which one do we have to download?

2. I installed the plugin for 2.0.10 and the yaml analyzer plugin and completed the setup. "cfn-nag-scan.nagscan" file is getting generated in my local through the command line. I tried to analyze cloud formation yaml files in SonarQube 8.9 but the file isn't being analyzed. There are a total of 177 rules for cloud formation that are showing as active in SonarQube.
I am using "sonar.cfn.nag.reportFiles=reports/cfn-nag-scan.nagscan" to analyze.

Is there anything else that I have to set up?

**Comment by pethers** [comment]
Hi,

1. To be able to get the plugin approved to be part of Sonarqube plugin I had to remove the language Cloudformation ( more details at https://community.sonarsource.com/t/new-release-sonar-cloudformation-plugin-1-0-2/14021/5 ) but still use it in an old system so release it once in a while to support new cfn-nag rules.

2. Have you enabed the Cloudformation rules in the Quality profile you have set as default for yaml, or set the Cloudformation yml rules as default ? 

Have a look at https://www.hack23.com/sonar/profiles, try set "Cloudformation Rules
BUILT-IN" as default quality profile for yaml.

If you already done all above, if you can provide some log output of the scan I might be able to figure out why it fails.

**Comment by ilyas-ixm** [comment]
I just set the Cloudformation rules as default. It's working now.

Thank you!

**Comment by pethers** [comment]
Also possible to create a custom quality profile for yaml, to include both cloudformation and any other yaml rules you want to include.
