### ISSUE TITLE
Add JAR file to release

### ISSUE THREAD

**Issue by Breee** [Hack23/sonar-cloudformation-plugin#382]
Greetings,

it would be great if you would add a JAR file to the latest release, such that we do not have to build the plugin on our own. 

Kind regards
Bree

**Comment by pethers** [comment]
Publish all jars to maven central, latest release https://search.maven.org/remotecontent?filepath=com/hack23/sonar/sonar-cloudformation-plugin/2.1.1/sonar-cloudformation-plugin-2.1.1.jar but will add the link to the release page as well. 

Thanks for the reminder.

**Comment by pethers** [comment]
All releases https://search.maven.org/artifact/com.hack23.sonar/sonar-cloudformation-plugin
