### ISSUE TITLE
New fields in cfn_nag

### ISSUE THREAD

**Issue by rinaudjaws** [Hack23/sonar-cloudformation-plugin#425]
**Describe the bug**

Starting 0.8.4 cfn_nag output format has new fields  .element_types, .name  within violation list. See https://github.com/stelligent/cfn_nag/pull/578/files. 

This results in errors in the scans:
```
WARN: Problem reading cfn nag report json:Unrecognized field "name" (class com.hack23.sonar.cloudformation.parser.CfnNagViolation), not marked as ignorable (5 known properties: "type", "id", "logical_resource_ids", "message", "line_numbers"])
 at [Source: (FileInputStream); line: 9, column: 20] (through reference chain: java.util.ArrayList[0]->com.hack23.sonar.cloudformation.parser.CfnNagScanReport["file_results"]->com.hack23.sonar.cloudformation.parser.CfnNagReport["violations"]->java.util.ArrayList[0]->com.hack23.sonar.cloudformation.parser.CfnNagViolation["name"])

```

**Comment by pethers** [comment]
Hi,

Thanks for reporting this, what version of the plugin are you using  ? 

Added configure(DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES, false) 
in https://github.com/Hack23/sonar-cloudformation-plugin/blob/master/src/main/java/com/hack23/sonar/cloudformation/reports/process/CfnNagScanReportReader.java

in the 2.15 release to make it more failsafe when tools changing formats.

**Comment by pethers** [comment]
Use https://www.hack23.com/sonar/dashboard?id=com.hack23.sonar%3Atest-project-with-reports for test and is using cfn-nag 0.8.8 on the jenkins server https://www.hack23.com/jenkins/job/Hack23/job/sonar-cloudformation-plugin/job/master/

**Comment by pethers** [comment]
Have created https://github.com/SonarSource/sonar-update-center-properties/pull/252 and started the process to get update-center updated with latest release at https://community.sonarsource.com/t/new-release-cloudformation-plugin-2-1-18/53107
