### ISSUE TITLE
Possible Security Problems

### ISSUE THREAD

**Issue by ctindall** [Hack23/sonar-cloudformation-plugin#56]
Hey there! I noticed some possible problems in some code in this repo. A quick summary of a few of them is below, but let me know if you're interested in seeing a full report or talking about cloud security in general.

---

**severity:** serious

**filename:** `./src/test/resources/aws-cross-account-manager-master.yml`

**line number(s):** [119]

**resource(s):** 

IAM role should not allow * action on its permissions policy

---

**severity:** warning

**filename:** `./src/test/resources/aws-cross-account-manager-master.yml`

**line number(s):** [252]

**resource(s):** 

IAM policy should not allow * resource

---

**severity:** warning

**filename:** `./src/test/resources/aws-cross-account-manager-master.yml`

**line number(s):** [687, 711, 728, 119]

**resource(s):** 

Resource found with an explicit name, this disallows updates that require replacement of this resource

---

**severity:** warning

**filename:** `./src/test/resources/aws-cross-account-manager-master.yml`

**line number(s):** [482, 489]

**resource(s):** 

S3 Bucket should have access logging configured

---

**severity:** warning

**filename:** `./src/test/resources/aws-cross-account-manager-master.yml`

**line number(s):** [482, 489]

**resource(s):** 

S3 Bucket should have encryption option set

**Comment by pethers** [comment]
This template is just used to test the cfn-nag integration with sonarqube. But thanks for the feedback, and good initiative to scan github repositories.
