### ISSUE TITLE
Separate out Azure Arm, Bicep from 'terraform' classifications in sonarqube?

### ISSUE THREAD

**Issue by munntjlx** [Hack23/sonar-cloudformation-plugin#575]
**Is your feature request related to a problem? Please describe.**
Currently the Azure findings and check from checkov are classified either as 'cloudformation' or 'terraform'. There should be a subcategory for 'bicep' and 'arm template' 

**Describe the solution you'd like**
Please re-classify and label Azure checkov hotspots as either 'bicep' for bicep templates, or 'arm' for Azure arm templates.

**Describe alternatives you've considered**
I am guessing I could write my own XML, but not sure as I havent' used sonarqube too much.

**Additional context**
None.

**Comment by pethers** [comment]
Sorry missed this, will close it since https://github.com/Hack23/sonar-cloudformation-plugin/issues/579 exist now.
