### ISSUE TITLE
Checkov Reports not imported into Sonarqube

### ISSUE THREAD

**Issue by harshanandmv** [Hack23/sonar-cloudformation-plugin#604]
Hi,

I am trying to import the checkov report into sonarqube with sonar-cloudformation-plugin.

I run this command and there is a result file generated called result_json.json
_checkov -d {toxinidir} -o json --compact --output-file-path {toxinidir}_

I then run the sonar-scanner with these options

    	_${SONAR_SCANNER_PATH}/sonar-scanner -Dsonar.projectKey=${PSNAME}:${SONAR_BRANCH} \
                                        -Dsonar.projectName=${PSNAME}_${SONAR_BRANCH} \
                                        -Dsonar.projectVersion=1.0 \
                                        -Dsonar.sourceEncoding=UTF-8 \
                                        -Dsonar.sources=Source/. \
					-Dsonar.python.version=3.7,3.8,3.9,3.10 \
					-Dsonar.python.coverage.reportPaths=Source/coverage.xml \
					**-Dsonar.checkov.reportFiles=Source/results_json.json \**
                                        -Dsonar.host.url=${SONARQUBE_URL} \
					-Dsonar.scm.disabled=true \
                                        -Dsonar.ws.timeout=300_

I see these logs in the build run:

15:53:11  WARN: Missing property:sonar.cfn.nag.reportFiles
15:53:11  INFO: sonar.checkov.reportFiles=Source/results_json.json
15:53:11  INFO: Processing  checkov :Source/results_json.json
15:53:11  INFO: Reading checkov reports:Source/results_json.json
15:53:12  INFO: Process iac reports (done) | time=257ms
15:53:12  INFO: Sensor Cloudformation Check [cloudformation] (done) | time=257ms

But I cannot see the results in the sonar dashboard. Am I missing something?

**Comment by pethers** [comment]
Have you enabled checkov rules in the cloudformation or terraform profile you are using ?

Example profile https://www.hack23.com/sonar/profiles/show?name=CIA+cloudformation&language=cloudformation

**Comment by pethers** [comment]
Also what version of the plugin are you using ?

**Comment by harshanandmv** [comment]
> Also what version of the plugin are you using ?

Plugin version: 3.0.8
Enabled checkov rules in cloudformation.

**Comment by pethers** [comment]
Looks like it find the checkov report file. 

--
[INFO] Processing  checkov :target/aws-cross-account-manager-master.checkov-report
[INFO] Reading checkov reports:target/aws-cross-account-manager-master.checkov-report
[INFO] Checkov scanned file :src/main/config/aws-cross-account-manager-master.yml
[INFO] Checkov scanned file :src/main/config/aws-cross-account-manager-master.yml
---

What checkov version are you using and its the cloudformation in sonar sources ?

**Comment by pethers** [comment]
Compared with test project at https://www.hack23.com/jenkins/job/Hack23/job/sonar-cloudformation-plugin/job/master/795/console

**Comment by harshanandmv** [comment]
My bad... There were no issues being reported by checkov and hence it was not being shown. Thanks for the support @pethers !!

**Comment by pethers** [comment]
Happy you figured it out :)
