### ISSUE TITLE
Sonar-scanner unable to parse generated checkov report

### ISSUE THREAD

**Issue by budgester** [Hack23/sonar-cloudformation-plugin#645]
Data at mentioned location in the report file.

```"caller_file_line_range": [1, 24],```

`WARN: Problem reading checkov report json:Cannot deserialize value of type `java.lang.String` from Array value (token `JsonToken.START_ARRAY`) at [Source: (StringReader); line: 1, column: 2902] (through reference chain: com.hack23.sonar.cloudformation.reports.checkov.CheckovReport["results"]->com.hack23.sonar.cloudformation.reports.checkov.CheckovResults["passed_checks"]->java.util.ArrayList[2]->com.hack23.sonar.cloudformation.reports.checkov.CheckovPassedCheck["caller_file_line_range"])`

**Comment by budgester** [comment]
```
15:08:28         _               _              
15:08:28     ___| |__   ___  ___| | _______   __
15:08:28    / __| '_ \ / _ \/ __| |/ / _ \ \ / /
15:08:28   | (__| | | |  __/ (__|   < (_) \ V / 
15:08:28    \___|_| |_|\___|\___|_|\_\___/ \_/  
15:08:28                                        
15:08:28  By bridgecrew.io | version: 2.2.93 
15:08:28  Update available 2.2.93 -> 2.2.157
15:08:28  Run pip3 install -U checkov to update 
15:08:28  
```

**Comment by budgester** [comment]
15:08:30  INFO: SonarScanner 4.7.0.2747

**Comment by pethers** [comment]
Found the issue with caller_file_line_range, the terraform/cloudformation templates used for test only had null values for caller_file_line_range . 

For the last error, how does the checkov report 
`  "entity_tags": {
                    "Name": "tf_test"
                },`
                
                part look in your report ?

**Comment by pethers** [comment]
Can release a new version once we fixed the last error as well.

**Comment by budgester** [comment]
` "entity_tags": {"Name": ["${var.application_name}-${var.rds_database_name}-aurora-sg"]},`

**Comment by pethers** [comment]
Have released https://github.com/Hack23/sonar-cloudformation-plugin/releases/tag/sonar-cloudformation-plugin-3.0.11 , hope this would fix the above issues.

Please test https://oss.sonatype.org/service/local/repositories/releases/content/com/hack23/sonar/sonar-cloudformation-plugin/3.0.11/sonar-cloudformation-plugin-3.0.11.jar

**Comment by budgester** [comment]
Thanks so much for looking at this, will test it with our sonar instance

**Comment by budgester** [comment]
Fixes are working.
